# Generated by Django 3.2.3 on 2021-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='uiid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
